# CMAKE generated file: DO NOT EDIT!
# Generated by "KDevelop3" Generator, CMake Version 2.2

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# Produce verbose output by default.
VERBOSE = 1

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/local/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = ../../../../../../home/belitz/work/trunk/evaltool

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = .

# Include make rules for object files.
include src/evaltool.dir/chausdorffdistance.o.build.make
include src/evaltool.dir/cmeandistance.o.build.make
include src/evaltool.dir/cdicecoefficient.o.build.make
include src/evaltool.dir/evaltool.o.build.make
include src/evaltool.dir/cregionsize.o.build.make

src/evaltool.dir/depend: src/evaltool.dir/chausdorffdistance.o.depend
src/evaltool.dir/depend: src/evaltool.dir/cmeandistance.o.depend
src/evaltool.dir/depend: src/evaltool.dir/cdicecoefficient.o.depend
src/evaltool.dir/depend: src/evaltool.dir/evaltool.o.depend
src/evaltool.dir/depend: src/evaltool.dir/cregionsize.o.depend

# Object files for target evaltool
evaltool_OBJECTS = \
"src/evaltool.dir/chausdorffdistance.o" \
"src/evaltool.dir/cmeandistance.o" \
"src/evaltool.dir/cdicecoefficient.o" \
"src/evaltool.dir/evaltool.o" \
"src/evaltool.dir/cregionsize.o"

# External object files for target evaltool
evaltool_EXTERNAL_OBJECTS =

src/evaltool: src/evaltool.dir/chausdorffdistance.o
src/evaltool: src/evaltool.dir/cmeandistance.o
src/evaltool: src/evaltool.dir/cdicecoefficient.o
src/evaltool: src/evaltool.dir/evaltool.o
src/evaltool: src/evaltool.dir/cregionsize.o
src/evaltool: /usr/lib/libz.so
src/evaltool: /usr/lib/libblitz.a
src/evaltool: /usr/lib/libxml++-2.6.so
src/evaltool: /usr/lib/libxml2.so
src/evaltool: /usr/lib/libglibmm-2.4.so
src/evaltool: src/evaltool.dir/build.make
	@echo "Linking CXX executable src/evaltool"
	c++   -funroll-loops -fmove-all-movables -fprefetch-loop-arrays -mcpu=pentium4 -march=pentium4 -mfpmath=sse -O3 -fPIC $(evaltool_OBJECTS) $(evaltool_EXTERNAL_OBJECTS)  -o src/evaltool -rdynamic -L/usr/X11R6/lib -L/usr/local/lib/vtk -L/home/belitz/lib -laipsbase -laipsfilehandlers -laipsbase -laipsfilehandlers -lMagick++ -lWand -lMagick -llcms -ltiff -lfreetype -ljasper -ljpeg -lpng -ldpstk -ldps -lXext -lXt -lSM -lICE -lX11 -lbz2 -lxml2 -lz -lpthread -lm -lpthread -lvtkIO -laipsbase -lz -lblitz -lm -lxml++-2.6 -lxml2 -lglibmm-2.4 -lm -lpthread -lMagick++ -Wl,-rpath,/home/belitz/lib 

# Convenience name for target.
src/evaltool.dir/build: src/evaltool

src/evaltool.dir/requires: src/evaltool.dir/chausdorffdistance.o.requires
src/evaltool.dir/requires: src/evaltool.dir/cmeandistance.o.requires
src/evaltool.dir/requires: src/evaltool.dir/cdicecoefficient.o.requires
src/evaltool.dir/requires: src/evaltool.dir/evaltool.o.requires
src/evaltool.dir/requires: src/evaltool.dir/cregionsize.o.requires

src/evaltool.dir/clean:
	$(CMAKE_COMMAND) -E remove -f $(evaltool_OBJECTS) src/evaltool

