# CMAKE generated file: DO NOT EDIT!
# Generated by "KDevelop3" Generator, CMake Version 2.2

# Force unix paths in dependencies.
SET(CMAKE_FORCE_UNIX_PATHS 1)

# The C and CXX include file search paths:
SET(CMAKE_C_INCLUDE_PATH
  "/home/belitz/include/aipsbase"
  "/usr/include/blitz"
  "/usr/include/libxml++-2.6"
  " /usr/include/libxml2/libxml"
  "/usr/include/glibmm-2.4"
  "/usr/lib/glibmm-2.4/include"
  "/usr/include/glib-2.0"
  "/usr/lib/glib-2.0/include"
  "/home/belitz/include/aipsfilehandlers"
  )
SET(CMAKE_CXX_INCLUDE_PATH ${CMAKE_C_INCLUDE_PATH})

# The C and CXX include file regular expressions for this directory.
SET(CMAKE_C_INCLUDE_REGEX_SCAN "^.*$")
SET(CMAKE_C_INCLUDE_REGEX_COMPLAIN "^$")
SET(CMAKE_CXX_INCLUDE_REGEX_SCAN ${CMAKE_C_INCLUDE_REGEX_SCAN})
SET(CMAKE_CXX_INCLUDE_REGEX_COMPLAIN ${CMAKE_C_INCLUDE_REGEX_COMPLAIN})
